name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cmake -B ${{github.workspace}}/build
        cmake --build ${{github.workspace}}/build
    - name: Test
      run: ./adopt_tests
      working-directory: ${{github.workspace}}/build
